# Generated by Django 4.2.7 on 2023-11-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_profile_is_student_profile_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='perfiles/default.png', upload_to='perfiles/')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('superusuario', 'Superusuario'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='profileluser',
            name='tipe_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipeuser'),
        ),
        migrations.AddField(
            model_name='profileluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
