# Generated by Django 4.2.7 on 2023-11-09 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_profileluser_tipeuser_delete_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilelUser',
            new_name='ProfileUser',
        ),
    ]
