# Generated by Django 4.2.7 on 2023-11-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_profileluser_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
