# Generated by Django 4.2.7 on 2023-11-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipeCourse',
            new_name='TypeCourse',
        ),
        migrations.RenameModel(
            old_name='TipeUser',
            new_name='TypeUser',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='tipe_course',
            new_name='type_course',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_tipe',
            new_name='user_type',
        ),
    ]
