# Generated by Django 4.2.7 on 2023-11-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
