# Generated by Django 4.2.7 on 2023-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courseimages/default.png', upload_to='courseimages/'),
        ),
    ]
