# Generated by Django 4.2.7 on 2023-11-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
