# Generated by Django 4.2.7 on 2023-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_question_answer_1_alter_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_html',
            field=models.TextField(blank=True),
        ),
    ]
