# Generated by Django 4.2.7 on 2023-11-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lesson_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressuser',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
